"""Initial schema with all tables

Revision ID: 47a04956d444
Revises: 
Create Date: 2026-03-14 10:15:08.067005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from core_inventory.models.types import GUID


# revision identifiers, used by Alembic.
revision: str = '47a04956d444'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('warehouse', 'rack', 'floor_area', name='locationtype'), nullable=False),
    sa.Column('parent_id', GUID(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('delivery_orders',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_contact', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'picking', 'packing', 'validated', name='deliveryorderstatus'), nullable=False),
    sa.Column('validated_by', GUID(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('move_history',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('product_id', GUID(), nullable=False),
    sa.Column('location_id', GUID(), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('receipt', 'delivery_order', 'transfer', 'stock_adjustment', 'initial_stock', name='documenttype'), nullable=False),
    sa.Column('document_id', sa.String(length=255), nullable=False),
    sa.Column('source_location_id', GUID(), nullable=True),
    sa.Column('destination_location_id', GUID(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_move_history_document_type'), 'move_history', ['document_type'], unique=False)
    op.create_index(op.f('ix_move_history_location_id'), 'move_history', ['location_id'], unique=False)
    op.create_index(op.f('ix_move_history_product_id'), 'move_history', ['product_id'], unique=False)
    op.create_index(op.f('ix_move_history_timestamp'), 'move_history', ['timestamp'], unique=False)
    op.create_table('receipts',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('supplier_contact', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'validated', name='receiptstatus'), nullable=False),
    sa.Column('validated_by', GUID(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('product_id', GUID(), nullable=False),
    sa.Column('location_id', GUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'location_id', name='uq_product_location')
    )
    op.create_index(op.f('ix_stock_location_id'), 'stock', ['location_id'], unique=False)
    op.create_index(op.f('ix_stock_product_id'), 'stock', ['product_id'], unique=False)
    op.create_table('stock_adjustments',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('product_id', GUID(), nullable=False),
    sa.Column('location_id', GUID(), nullable=False),
    sa.Column('recorded_quantity', sa.Integer(), nullable=False),
    sa.Column('physical_quantity', sa.Integer(), nullable=False),
    sa.Column('adjustment_difference', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('pending', 'validated', name='stockadjustmentstatus'), nullable=False),
    sa.Column('validated_by', GUID(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_ledger',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('product_id', GUID(), nullable=False),
    sa.Column('location_id', GUID(), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('running_balance', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('receipt', 'delivery_order', 'transfer', 'stock_adjustment', 'initial_stock', name='documenttype'), nullable=False),
    sa.Column('document_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_ledger_location_id'), 'stock_ledger', ['location_id'], unique=False)
    op.create_index(op.f('ix_stock_ledger_product_id'), 'stock_ledger', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_ledger_timestamp'), 'stock_ledger', ['timestamp'], unique=False)
    op.create_table('transfers',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('source_location_id', GUID(), nullable=False),
    sa.Column('destination_location_id', GUID(), nullable=False),
    sa.Column('product_id', GUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'validated', name='transferstatus'), nullable=False),
    sa.Column('validated_by', GUID(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_order_items',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('delivery_order_id', GUID(), nullable=False),
    sa.Column('product_id', GUID(), nullable=False),
    sa.Column('location_id', GUID(), nullable=False),
    sa.Column('requested_quantity', sa.Integer(), nullable=False),
    sa.Column('delivered_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_order_id'], ['delivery_orders.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_order_items_delivery_order_id'), 'delivery_order_items', ['delivery_order_id'], unique=False)
    op.create_table('receipt_items',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('receipt_id', GUID(), nullable=False),
    sa.Column('product_id', GUID(), nullable=False),
    sa.Column('location_id', GUID(), nullable=False),
    sa.Column('expected_quantity', sa.Integer(), nullable=False),
    sa.Column('received_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_items_receipt_id'), 'receipt_items', ['receipt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_items_receipt_id'), table_name='receipt_items')
    op.drop_table('receipt_items')
    op.drop_index(op.f('ix_delivery_order_items_delivery_order_id'), table_name='delivery_order_items')
    op.drop_table('delivery_order_items')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_stock_ledger_timestamp'), table_name='stock_ledger')
    op.drop_index(op.f('ix_stock_ledger_product_id'), table_name='stock_ledger')
    op.drop_index(op.f('ix_stock_ledger_location_id'), table_name='stock_ledger')
    op.drop_table('stock_ledger')
    op.drop_table('stock_adjustments')
    op.drop_index(op.f('ix_stock_product_id'), table_name='stock')
    op.drop_index(op.f('ix_stock_location_id'), table_name='stock')
    op.drop_table('stock')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_move_history_timestamp'), table_name='move_history')
    op.drop_index(op.f('ix_move_history_product_id'), table_name='move_history')
    op.drop_index(op.f('ix_move_history_location_id'), table_name='move_history')
    op.drop_index(op.f('ix_move_history_document_type'), table_name='move_history')
    op.drop_table('move_history')
    op.drop_table('delivery_orders')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_table('locations')
    # ### end Alembic commands ###
